---

- name: "Install Oracle XE"
  hosts: oraclexe
  user: root
  become: yes

  roles:
     - role: ansible-oracle-xe

  environment:
    ORACLE_HOME: /u01/app/oracle/product/11.2.0/xe
    ORACLE_SID: XE
