---

- name: "Template script.sql"
  template:
     src: script.sql
     dest: /tmp/script.sql

- name: "Execute script.sql"
  shell: /u01/app/oracle/product/11.2.0/xe/bin/sqlplus "sys/sys as sysdba" @/tmp/script.sql

- name: "Delete script.sql"
  file: 
    path: /tmp/script.sql
    state: absent  

- name: "Create un4 directory"
  file:
    path: /u01/app/oracle/oradata/un4
    state: directory
    owner: oracle
    group: dba

- name: "Template tablespace.sql"
  template:
     src: tablespace.sql
     dest: /tmp/tablespace.sql

- name: "Execute tablespace.sql"
  shell: /u01/app/oracle/product/11.2.0/xe/bin/sqlplus "sys/sys as sysdba" @/tmp/tablespace.sql
